### ISSUE TITLE
[improvement]: in the response after creating URLs, share full shortURL

### ISSUE THREAD

**Issue by championswimmer** [championswimmer/onepixel_backend#53]
Current response looks like this 
<img width="375" alt="image" src="https://github.com/championswimmer/onepixel_backend/assets/1327050/48751fb0-68b6-425e-80bd-26ccdcd14a2a">

Make the "short_url" field have the "https://1px.li/" prefix so that it is a full link. 

Pick it from config.

**Comment by amanjha8100** [comment]
Hi @championswimmer (Arnav). I am planning to pick this up. Will be checking out the repo also, and will raise the PR, once I get the understanding of the codebase.

**Comment by amanjha8100** [comment]
Hi @championswimmer ( Arnav ). I was going through the code base and had quite a debugging session while authenticating my JWT token when I was making api call using postman, which sets JWT Token to be as "Bearer <Token>". 

Unfortunately, we are passing the token directly into the ValidateJwt(authHeader) without removing the "Bearer" part of it. This was making the JWT token to fail validations and return error as "malformed token".

I had to optimise the input to ValidateJWT a bit in "MandatoryJwtAuthMiddleware" in middlewares.go file as such to remove "Bearer " from the received token.

`func MandatoryJwtAuthMiddleware(c *fiber.Ctx) error {
	authHeader := c.Get("Authorization")
	const BEARER_SCHEMA = "Bearer "
	if authHeader == "" {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"message": "Unauthorized: No Authorization header provided",
		})
	}
	authHeader = authHeader[len(BEARER_SCHEMA):]
	user, err := ValidateJWT(authHeader)

	if err != nil {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"message": "Unauthorized: Invalid JWT token" + err.Error(),
		})
	}
	c.Locals("user", user)
	return c.Next()
}`

I am not sure if this is a mistake from my side. I would like to have your views on this.

Thanks In advance. If I sounded naive because of my lack of knowledge, please forgive me. 😢 

I will raise the PR of the above issue, when you assign it to me. Thank you! Have a great Monday. 😄

**Comment by amanjha8100** [comment]
@akshat2602 Just a question, do we not wait for the issues to be assigned, before raising a PR. Felt violated here. 😢

**Comment by akshat2602** [comment]
Ohhh! I'm sorry I didn't see the conversation here. I had a look on the issue yesterday and just started on a fix. You're always welcome to pick up other issues as well! :sweat_smile:
