### ISSUE TITLE
[api] POST /users/ to signup

### ISSUE THREAD

**Issue by championswimmer** [championswimmer/onepixel_backend#6]

**Comment by shawshankkumar** [comment]
What kind of sign up auth are we looking at? 

email pass?
google oauth?

**Comment by FaizBShah** [comment]
Hey @championswimmer, can I restructure the folder and file structures a little bit? For example, I feel the entities should actually be referred as models and be inside the models package, and the stuffs which we are referring as models are actually just DTO, so it should be inside a dto package, if that makes sense. Also, thinking about handling errors instead of just lo.Must() while doing this PR. Is that ok, or should I tone it down?

**Comment by championswimmer** [comment]
@FaizBShah 

1. yes dto and models is right, that should change. you can send 1 PR just to rename that - happy to accept that 

2. handling errors - I want to keep things lo.Must wherever the error _should be_ crashing the server (there are things that must be fatal in nature) for everything else, yes should be handled. for example, if we are unable to connect to db, it should be fatal and starting the server has no point in that scenario.

**Comment by FaizBShah** [comment]
Cool, got it!!! Raising a PR for the folder structure change

**Comment by lohit97** [comment]
Raised [PR#9](https://github.com/championswimmer/onepixel_backend/pull/9) for User SignUp.


Can add - Email Regex Check,  Domain Lookup, Email Verification.
